import { Heart } from "@/components/icons/heart";
import { Menu } from "@/components/icons/menu";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogClose,
  DialogTrigger,
  SideMenuDialogContent,
} from "@/components/ui/dialog";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";
import { fetchFolders } from "@/lib/data";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function SideMenu() {
  const folders = await fetchFolders();

  return (
    <div className="space-y-1">
      <Button
        asChild
        variant="ghost"
        className="w-full justify-start flex gap-2"
      >
        <Link href="/gallery">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            strokeWidth={1.5}
            stroke="currentColor"
            className="w-6 h-6"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z"
            />
          </svg>
          Gallery
        </Link>
      </Button>
      <Accordion type="single" collapsible className="w-full">
        <AccordionItem value="item-1" className="border-b-0">
          <AccordionTrigger className="py-0">
            <Button
              asChild
              variant="ghost"
              className="w-full justify-start flex gap-2"
            >
              <Link href="/albums">
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  fill="none"
                  viewBox="0 0 24 24"
                  strokeWidth={1.5}
                  stroke="currentColor"
                  className="w-6 h-6"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    d="M2.25 12.75V12A2.25 2.25 0 0 1 4.5 9.75h15A2.25 2.25 0 0 1 21.75 12v.75m-8.69-6.44-2.12-2.12a1.5 1.5 0 0 0-1.061-.44H4.5A2.25 2.25 0 0 0 2.25 6v12a2.25 2.25 0 0 0 2.25 2.25h15A2.25 2.25 0 0 0 21.75 18V9a2.25 2.25 0 0 0-2.25-2.25h-5.379a1.5 1.5 0 0 1-1.06-.44Z"
                  />
                </svg>
                Albums
              </Link>
            </Button>
          </AccordionTrigger>
          <AccordionContent>
            {folders.map((folder) => (
              <Button
                variant="ghost"
                asChild
                key={folder.name}
                className="w-full justify-start flex gap-2"
              >
                <Link className="pl-8" href={`/albums/${folder.path}`}>
                  {folder.name}
                </Link>
              </Button>
            ))}
          </AccordionContent>
        </AccordionItem>
      </Accordion>
      <Button
        asChild
        variant="ghost"
        className="w-full justify-start flex gap-2"
      >
        <Link href="/favorites">
          <Heart />
          Favorites
        </Link>
      </Button>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="border-b">
          <div className="flex h-16 items-center container mx-auto">
            <Link href="/" className="hidden sm:flex items-center">
              <Image
                src="/album.png"
                alt="icon of this photo album app"
                width="50"
                height="50"
              />
              MEDIAS APP
            </Link>
            <div className="sm:ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage
                  src="https://github.com/shadcn.png"
                  alt="@shadcn"
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>

              <div className="lg:hidden">
                <Dialog>
                  <DialogTrigger asChild>
                    <Button
                      variant="ghost"
                      className="border border-input hover:bg-accent hover:text-accent-foreground"
                    >
                      <Menu />
                    </Button>
                  </DialogTrigger>

                  <SideMenuDialogContent>
                    <nav className="mt-5 flex-1 px-2 space-y-1">
                      <SideMenu />
                    </nav>
                    <div className="flex flex-col-reverse sm:flex-row sm:justify-end sm:space-x-2 mt-5">
                      <DialogClose className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-10 px-4 py-2">
                        Close
                      </DialogClose>
                    </div>
                  </SideMenuDialogContent>
                </Dialog>
              </div>
            </div>
          </div>
        </div>

        <div className="grid lg:grid-cols-5 gap-4 container">
          <div className="pb-12 hidden lg:block">
            <div className="space-y-4 py-4">
              <div className="pr-4 py-2">
                <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
                  Manage
                </h2>
                <SideMenu />
              </div>
            </div>
          </div>
          <div className="col-span-3 lg:col-span-4 pt-8">{children}</div>
        </div>
        <Toaster />
      </body>
    </html>
  );
}
